id_dataset_file_name: "exp_1_id_alfred.csv"

### Valid OOD test sets:
# + exp_2_ood_complex_tasks.csv
# + exp_2_ood_industrial_domain.csv
ood_dataset_file_name: "exp_2_ood_industrial_domain.csv"

### Valid model_ids:
# + Llama-2-7b-hf
# + CodeLlama-7b-Instruct-hf
# + Mistral-7B-Instruct-v0.2
# + gpt-4
# + gpt-3.5-turbo-instruct
model_id: "CodeLlama-7b-Instruct-hf"

### Valid task instruction types:
# + rp
# + minimal
# + llama-7b
# + codellama
# + mistral
# + gpt
task_instruction_type: "minimal"

# train-test-split
num_train_exs: 25

# Where to save .csv file of results (includes decoded outputs and BLEU scores)
exp_dir: "experiment_2/"